### ISSUE TITLE
Only CSS and JS file

### ISSUE THREAD

**Issue by PooLP** [yohanb/spsave-webpack-plugin#1]
Hi,

Your plugin upload only js and css files, but not images or all custom files ex:.master or .aspx (I copy them with copy-webpack-plugin or using require () / Import in ts / js files).

I have a little look at your code but I do not know too much about the webpack plugin API.

Thanks,
Richard

**Comment by yohanb** [comment]
Hi Richard,
The plugin's focus is to upload assets generated by webpack.
If you want to copy other assets, I suggest you use the spsave plugin directly.
Cheers,
Yohan
